-- =====================================================================
-- PlateHunter KSA — Phase 1 schema
-- Run this in the Supabase SQL editor for your project.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Agent profiles (one row per auth user, created by an admin)
-- ---------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username text unique not null,
  role text not null default 'agent' check (role in ('admin', 'agent')),
  is_active boolean not null default true,

  -- Device lock: set automatically on first successful login.
  -- An admin clears this column to "release" the account for a new device.
  device_fingerprint text,

  -- Single active session: every successful login rotates this token.
  -- The client compares its locally-stored token against this value and
  -- signs itself out if another login has overwritten it.
  session_token uuid,

  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

-- An agent can read only their own profile row.
create policy "profiles_select_own"
  on public.profiles for select
  using (auth.uid() = id);

-- Admins can read every profile (for the device-reset / agent management screen).
create policy "profiles_select_admin"
  on public.profiles for select
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );

-- Admins can update any profile (e.g. clear device_fingerprint to reset a device,
-- deactivate an agent, etc).
create policy "profiles_update_admin"
  on public.profiles for update
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );

-- ---------------------------------------------------------------------
-- 2. Device binding + single-session RPC
--
-- Called once per login from the client with the device fingerprint
-- generated by lib/device.ts. Runs with the owner's privileges
-- (security definer) so the binding logic can't be bypassed by a
-- client that only has the anon key.
-- ---------------------------------------------------------------------
create or replace function public.handle_device_login(p_device_fingerprint text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile public.profiles%rowtype;
  v_new_token uuid := gen_random_uuid();
begin
  select * into v_profile from public.profiles where id = auth.uid();

  if v_profile.id is null then
    raise exception 'PROFILE_NOT_FOUND';
  end if;

  if v_profile.is_active = false then
    raise exception 'ACCOUNT_DISABLED';
  end if;

  -- Admins are exempt from the device lock — they can sign in from any
  -- device/location. Still rotates the session token like everyone else.
  if v_profile.role = 'admin' then
    update public.profiles
      set session_token = v_new_token
      where id = auth.uid();
    return v_new_token;
  end if;

  -- First login on this account: bind the device.
  if v_profile.device_fingerprint is null then
    update public.profiles
      set device_fingerprint = p_device_fingerprint,
          session_token = v_new_token
      where id = auth.uid();
    return v_new_token;
  end if;

  -- Existing binding must match this device.
  if v_profile.device_fingerprint <> p_device_fingerprint then
    raise exception 'DEVICE_MISMATCH';
  end if;

  -- Same device: rotate the session token, invalidating any other
  -- currently-open session for this account.
  update public.profiles
    set session_token = v_new_token
    where id = auth.uid();

  return v_new_token;
end;
$$;

grant execute on function public.handle_device_login(text) to authenticated;

-- ---------------------------------------------------------------------
-- 3. Realtime: allow clients to subscribe to their own profile row so
--    the SessionGuard component can detect a session_token change
--    (i.e. a login from another device) and force a logout.
-- ---------------------------------------------------------------------
alter publication supabase_realtime add table public.profiles;

-- ---------------------------------------------------------------------
-- 4. Seed example (run manually, after creating the matching auth user
--    via Supabase Auth -> Users -> Add user, email: agent01@platehunter.local)
-- ---------------------------------------------------------------------
-- insert into public.profiles (id, username, role)
-- values ('<auth-user-uuid>', 'agent01', 'agent');
